name: Deploy

on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # Setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.ARR }}" > "$HOME/.ssh/id_rsa"
      - run: chmod 600 "$HOME/.ssh/id_rsa"
      # Build
      - run: npm install
      - run: npm run build
      # Deploy
      - run: cd public && rsync -rv -e "ssh -o StrictHostKeyChecking=no" --archive --compress --delete . www@178.21.11.126:/home/www/
